#!/usr/bin/env node
// Turn one or more SVG files into a TypeScript module of path data + bounding
// boxes, so artwork can be animated per path in Remotion (see SvgArt.tsx).
//
//   node svg_to_paths.mjs --out src/logo/paths.ts dog=logo-dog.svg lemon=logo-lemon.svg
//   node svg_to_paths.mjs --report logo-dog.svg          # print a bbox table only
//
// The report lists every path's index, fill, position and size. Use it to
// decide which indices form which part (wordmark letters, body, eyes...).
// Gradient fills (url(#id)) are replaced by their first stop colour, or grey.
import fs from "node:fs";

const args = process.argv.slice(2);
let out = null;
let report = false;
const inputs = [];
for (let i = 0; i < args.length; i++) {
  if (args[i] === "--out") out = args[++i];
  else if (args[i] === "--report") report = true;
  else inputs.push(args[i]);
}
if (inputs.length === 0) {
  console.error("usage: svg_to_paths.mjs [--out file.ts] [--report] name=file.svg ...");
  process.exit(1);
}

const parse = (file) => {
  const s = fs.readFileSync(file, "utf8");
  const stops = {};
  for (const g of s.matchAll(/<(linearGradient|radialGradient)[^>]*id="([^"]+)"[^>]*>([\s\S]*?)<\/\1>/g)) {
    const m = g[3].match(/stop-color="([^"]+)"|stop-color:\s*([^;"]+)/);
    stops[g[2]] = m ? m[1] || m[2] : "#9A9AA8";
  }
  const other = s.match(/<(rect|circle|ellipse|polygon|polyline|line|use|image|text)\b/g);
  if (other) console.warn(`${file}: contains ${[...new Set(other)].join(", ")} — only <path> elements are exported; convert shapes to paths in the editor if they matter`);
  const paths = [];
  for (const m of s.matchAll(/<path\b([^>]*)\/?>/g)) {
    const attrs = m[1];
    const d = attrs.match(/\sd="([^"]+)"/)?.[1];
    if (!d) continue;
    let fill = attrs.match(/\sfill="([^"]+)"/)?.[1] ?? "#000000";
    if (fill === "white") fill = "#FFFFFF";
    if (fill === "black") fill = "#000000";
    const grad = fill.match(/url\(#([^)]+)\)/);
    if (grad) fill = stops[grad[1]] ?? "#9A9AA8";
    const nums = d.match(/-?\d*\.?\d+(?:e-?\d+)?/g).map(Number);
    const xs = [], ys = [];
    for (let k = 0; k + 1 < nums.length; k += 2) { xs.push(nums[k]); ys.push(nums[k + 1]); }
    const box = [Math.min(...xs), Math.min(...ys), Math.max(...xs), Math.max(...ys)].map(Math.round);
    paths.push({ d, fill, box });
  }
  const box = [
    Math.min(...paths.map((p) => p.box[0])), Math.min(...paths.map((p) => p.box[1])),
    Math.max(...paths.map((p) => p.box[2])), Math.max(...paths.map((p) => p.box[3])),
  ];
  return { box, paths };
};

let ts = "// AUTO-GENERATED by svg_to_paths.mjs — do not edit by hand.\n";
ts += "export type SvgPath = { d: string; fill: string; box: [number, number, number, number] };\n";
ts += "export type SvgData = { box: [number, number, number, number]; paths: SvgPath[] };\n";
for (const input of inputs) {
  const eq = input.indexOf("=");
  const name = eq > 0 ? input.slice(0, eq) : input.replace(/.*\//, "").replace(/\W.*$/, "");
  const file = eq > 0 ? input.slice(eq + 1) : input;
  const data = parse(file);
  console.error(`${name}: ${data.paths.length} paths, art box ${data.box.join(",")}`);
  if (report || !out) {
    console.log(`\n=== ${name} (${file})\nidx\tfill\tx,y\tw x h`);
    data.paths.forEach((p, i) => console.log(`${i}\t${p.fill}\t${p.box[0]},${p.box[1]}\t${p.box[2] - p.box[0]}x${p.box[3] - p.box[1]}`));
  }
  ts += `\nexport const ${name}: SvgData = ${JSON.stringify(data)};\n`;
}
if (out) {
  fs.mkdirSync(out.replace(/\/[^/]+$/, ""), { recursive: true });
  fs.writeFileSync(out, ts);
  console.error(`wrote ${out} (${(ts.length / 1024).toFixed(0)} KB)`);
}
